### ISSUE TITLE
demo code not working

### ISSUE THREAD

**Issue by hzwus** [techartorg/bqt#102]
Hi there, I followed the instructions to install bqt from pip as a module. I can succesfully import bqt, however when I run any of the demos, I get the following error message because there is no QApplication instance defined.

`AttributeError: 'NoneType' object has no attribute 'blender_widget'`

I see that this [same error was posted in the past](https://github.com/techartorg/bqt/issues/18), but the solution seems to be outdated (the bqt_startup.py script has since been removed)? I tried running `setup.py` as well as the old `bqt_startup.py`, hoping that they would help register and instantiate the QApplication instance, but both scripts cause Blender to crash immediately.

I also tried installing bqt as an add-on instead, but have the same error.

This is happening on Blender 3.6 as well as 3.5! Anyone know what might be happening?

**Comment by hannesdelbeke** [comment]
That error implies that `QApplication.instance()` is None, so bqt hasn't started.
It's really weird that it doesn't work when you have the addon installed. Since the addon should automatically take care of this startup code. 
- Have you ensured the addon is enabled in Blender-preferences?
- Can you toggle your console, and see if any errors print on startup. A script error could prevent the startup from running. ![console instructions](https://i.stack.imgur.com/hK3bu.jpg)

`setup.py` confusingly doesn't setup bqt, it instead contains the packaging info for PyPI & pip install.

**Comment by hannesdelbeke** [comment]
Also note that the demo code has been moved out of bqt
So this `from bqt import hello_world` won't work anymore.
You now have to manually install the demo code.

**Comment by martin-dgg** [comment]
Hello, I am facing a similar Problem. 
I tried installing from pip and that didn't work. 
I got the message "Defaulting to user installation because normal site-packages is not writeable"
Tough not sure if that is related.

I also tried installing trough plugget. Facing this error:
ERROR:root:There was an install error for package 'blender-qt-stylesheet'
ERROR:root:

everything else is collected fine and it gives back a successfull install.

**Comment by hannesdelbeke** [comment]
Hi, can you share the exact pip install commands you used

**Comment by hannesdelbeke** [comment]
And is there any more log info for the plugget install?

**Comment by martin-dgg** [comment]
Pip command:
cd into C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\bin
then python -m pip install bqt

log from plugget install:
`PackagesMeta(bqt - not installed)
app_path C:\Users\MARTIN~1\AppData\Local\Temp\plugget\plugget-pkgs\blender
install requirements to target C:\Users\<my-user-name>\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\modules
Cloning into 'C:\Users\MARTIN~1\AppData\Local\Temp\plugget\blender\e1dcb275\bqt\latest\bqt'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 36 (delta 1), reused 14 (delta 0), pack-reused 0
Receiving objects: 100% (36/36), 31.55 KiB | 31.55 MiB/s, done.
Resolving deltas: 100% (1/1), done.

requirements.txt found: 'C:\Users\MARTIN~1\AppData\Local\Temp\plugget\blender\e1dcb275\bqt\latest\bqt\requirements.txt'
requirements.txt found:  C:\Users\MARTIN~1\AppData\Local\Temp\plugget\blender\e1dcb275\bqt\latest\bqt\requirements.txt
installing 'PySide6' from requirements.txt
run_command_process command: ['C:\\Program Files\\Blender Foundation\\Blender 4.1\\4.1\\python\\bin\\python.exe', '-m', 'pip', 'install', 'blender-qt-stylesheet', '--upgrade', '--target', 'C:\\Users\\<my-user-name>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\modules', '--no-user']
ERROR:root:There was an install error for package 'blender-qt-stylesheet'
ERROR:root:
ERROR:root:[notice] A new release of pip is available: 23.2.1 -> 24.1.2
ERROR:root:[notice] To update, run: C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\bin\python.exe -m pip install --upgrade pip
Collecting blender-qt-stylesheet
  Obtaining dependency information for blender-qt-stylesheet from https://files.pythonhosted.org/packages/ec/36/008533dc3738699f37a424ce33e8a6ffdcdc20a0a94877e41676bf0d917c/blender_qt_stylesheet-0.0.3-py3-none-any.whl.metadata
  Using cached blender_qt_stylesheet-0.0.3-py3-none-any.whl.metadata (22 kB)
Collecting qtpy (from blender-qt-stylesheet)
  Obtaining dependency information for qtpy from https://files.pythonhosted.org/packages/7e/a9/2146d5117ad8a81185331e0809a6b48933c10171f5bac253c6df9fce991c/QtPy-2.4.1-py3-none-any.whl.metadata
  Using cached QtPy-2.4.1-py3-none-any.whl.metadata (12 kB)
Collecting packaging (from qtpy->blender-qt-stylesheet)
  Obtaining dependency information for packaging from https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl.metadata
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Using cached blender_qt_stylesheet-0.0.3-py3-none-any.whl (45 kB)
Using cached QtPy-2.4.1-py3-none-any.whl (93 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Installing collected packages: packaging, qtpy, blender-qt-stylesheet
Successfully installed blender-qt-stylesheet-0.0.3 packaging-24.1 qtpy-2.4.1

installing 'blender-qt-stylesheet' from requirements.txt
run_command_process command: ['C:\\Program Files\\Blender Foundation\\Blender 4.1\\4.1\\python\\bin\\python.exe', '-m', 'pip', 'install', 'blender-qt-stylesheet', '--upgrade', '--target', 'C:\\Users\\<my-user-name>\\AppData\\Roaming\\Blender Foundation\\Blender\\4.1\\scripts\\modules', '--no-user']
ERROR:root:There was an install error for package 'blender-qt-stylesheet'
ERROR:root:
ERROR:root:[notice] A new release of pip is available: 23.2.1 -> 24.1.2
ERROR:root:[notice] To update, run: C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\bin\python.exe -m pip install --upgrade pip
Collecting blender-qt-stylesheet
  Obtaining dependency information for blender-qt-stylesheet from https://files.pythonhosted.org/packages/ec/36/008533dc3738699f37a424ce33e8a6ffdcdc20a0a94877e41676bf0d917c/blender_qt_stylesheet-0.0.3-py3-none-any.whl.metadata
  Using cached blender_qt_stylesheet-0.0.3-py3-none-any.whl.metadata (22 kB)
Collecting qtpy (from blender-qt-stylesheet)
  Obtaining dependency information for qtpy from https://files.pythonhosted.org/packages/7e/a9/2146d5117ad8a81185331e0809a6b48933c10171f5bac253c6df9fce991c/QtPy-2.4.1-py3-none-any.whl.metadata
  Using cached QtPy-2.4.1-py3-none-any.whl.metadata (12 kB)
Collecting packaging (from qtpy->blender-qt-stylesheet)
  Obtaining dependency information for packaging from https://files.pythonhosted.org/packages/08/aa/cc0199a5f0ad350994d660967a8efb233fe0416e4639146c089643407ce6/packaging-24.1-py3-none-any.whl.metadata
  Using cached packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Using cached blender_qt_stylesheet-0.0.3-py3-none-any.whl (45 kB)
Using cached QtPy-2.4.1-py3-none-any.whl (93 kB)
Using cached packaging-24.1-py3-none-any.whl (53 kB)
Installing collected packages: packaging, qtpy, blender-qt-stylesheet
Successfully installed blender-qt-stylesheet-0.0.3 packaging-24.1 qtpy-2.4.1

copy files to C:\Users\<my-user-name>\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons
C:\Users\<user-name>\AppData\Local\Temp\plugget\blender\e1dcb275\bqt\latest\bqt\bqt
BQT failed to import PySide
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\<my-user-name>\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\bqt\__init__.py", line 8, in <module>
    import bqt.manager
  File "C:\Users\<my-user-name>\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\bqt\manager.py", line 7, in <module>
    from bqt.qt_core import QApplication, QDockWidget, QtCore
ImportError: cannot import name 'QApplication' from 'bqt.qt_core' (C:\Users\<my-user-name>\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\bqt\qt_core.py)`

tough to be honest I think the import error was not there the first time I tried it.
I always had the problem that the addon didn't work on blender startup. I had to manually uninstall and then install using plugget to get it to work. Then I tried with the pip install and now neither works.

**Comment by martin-dgg** [comment]
Update:
the manual install described here: https://github.com/techartorg/bqt/wiki/install-bqt-addon
worked for me. 
If there is still an interest in finding out what went wrong before I'm happy to assist with that :)

**Comment by hannesdelbeke** [comment]
Thx. Ye i m not sure if that pip i stall would work. : 

This is the pip i stall command from plugget.
You can see it sets a target dir.
```
'C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\bin\python.exe', '-m', 'pip', 'install', 'blender-qt-stylesheet', '--upgrade', '--target', 'C:\Users\\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\modules', '--no-user']
```

You had an error 
> Defaulting to user installation because normal site-packages is not writeable"

I believe the site packages that the blender python is trying to install to, is in the `program files/blender` install folder.
And the user golder it backs up to on failure, is the python roaming site packages, not blender roaming in app data.

**Comment by hannesdelbeke** [comment]
Hmm i m not sure if what i said above is correct, just checked the manual install page and we don't set a target path there. 🤔

I ll also look into why plugget failed
