### ISSUE TITLE
Qthead: not correct context

### ISSUE THREAD

**Issue by atticus-lv** [techartorg/bqt#103]
I try to use qthread to import more than model files (so the will not blocking the qt window)
but with the temp_overide context, still remind the context is not correct.
However, instead of calling qthread, call it with a button(which block the qt window) works well

Here is the thread code
```python 
class ThreadImport(QThread):
    start_signal = Signal()
    finish_signal = Signal()
    success_signal = Signal(str)
    error_signal = Signal(str)

    progress_signal = Signal(int)

    files = []

    importer = {
        'obj': 'bpy.ops.wm.obj_import',
        'stl': 'bpy.ops.import_mesh.stl',
        'fbx': 'bpy.ops.import_scene.fbx',
    }

    def __init__(self, files, parent=None):
        super().__init__(parent=parent)
        self.files = files

    def run(self):
        self.start_signal.emit()

        for i, file in enumerate(self.files):
            ext = os.path.splitext(file)[1][1:]
            ext = ext.lower()

            if ext in self.importer:
                try:
                    with bpy.context.temp_override(window=bpy.context.window_manager.windows[0]):
                        cmd = self.importer[ext] + f"(filepath='{file}')"
                        print(cmd)
                        exec(cmd)

                    self.success_signal.emit(f'Import {file.split("/")[-1]}')

                except Exception as e:
                    print(e)
                    self.error_signal.emit(e)

            self.progress_signal.emit(int(i / len(self.files) * 100))

        self.finish_signal.emit()
```

**Comment by hannesdelbeke** [comment]
Blender doesn't officially support multithreading.
See the docs
https://docs.blender.org/api/current/info_gotcha.html#strange-errors-when-using-the-threading-module

There might be ways to get it to work but you are in uncharted territory. Believe this wont be something bqt can do. You could however use blender modal timers
 See https://blender.stackexchange.com/questions/47138/how-to-run-a-python-script-without-locking-blender

**Comment by atticus-lv** [comment]
However, using the import operator in modal will still block ther interface
It seems that the interface and the calling the import operator api is on ther same thread.

**Comment by hannesdelbeke** [comment]
if you want the UI to stay responsive while Blender imports, you might want to run it from outside of Blender. And set up a way of communication over a server. similar to what [PyBlish QML](https://github.com/pyblish/pyblish-qml) does
