### ISSUE TITLE
Cannot download bqt with plugget

### ISSUE THREAD

**Issue by siolavL** [techartorg/bqt#107]
Hi, I am trying to download bqt through the Plugget add-on. I received the following error:

![image](https://github.com/techartorg/bqt/assets/25291375/6c515830-cad4-4502-a116-9f7e9c4c4447)

If it is important context, I am using Windows. Please let me know if you have any input, I am unsure how to troubleshoot this myself. Thank you!

**Comment by hannesdelbeke** [comment]
Hi, thanks for reporting this issue. The earliest I can have a look at it is next week. Will post here with updates

**Comment by hannesdelbeke** [comment]
hi this error was fixed on 12 june, it seems you have a slightly outdated version of plugget installed from the screenshot you posted.

I would suggest to uninstall plugget, by going to this path and deleting the plugget folder.
![image](https://github.com/techartorg/bqt/assets/3758308/92d79422-eb59-45e0-8dcd-adf75e03a0d3)

then restart blender, and reinstall plugget as usual.
let me know if that fixed the problem for you.

**Comment by hannesdelbeke** [comment]
(feel free to reopen this if this did not fix the issue)
