### ISSUE TITLE
QFileDialog seems broken since 1.3.1

### ISSUE THREAD

**Issue by ElgoogUdiab** [techartorg/bqt#116]
When I am trying to create a Open File dialog using the following code snippet:
```python3
QtWidgets.QFileDialog.getOpenFileName(None, "Choose Package", "", "Zip Files (*.zip)")
```
it seems that two window are created: a normal windows containing normal file dialog content and an empty window. The first one (the normal one) will only show up for less than a second and then disappear, and the second one (the empty one) will be left behind.

This behavior shows up since 1.3.1 and it works fine on 1.3.0.

**Comment by hannesdelbeke** [comment]
this sounds like a bug with the auto parenting, a workaround is to disable this with the env var `BQT_AUTO_ADD` set to `0`
see https://github.com/techartorg/bqt/wiki/Environment-variables

i ll have a test myself and see if i can submit a fix

**Comment by hannesdelbeke** [comment]
i had a look at the changelog between 1.3.0 and 1.3.1 (thanks a lot for providing versions, this helps a lot)
it seems this was when the auto dockable wrap was added. 

you can work around this by setting `BQT_DOCKABLE_WRAP` to `0`
see https://github.com/techartorg/bqt/wiki/Environment-variables

**Comment by ElgoogUdiab** [comment]
> ### work around
> you can work around this by setting `BQT_DOCKABLE_WRAP` to `0` see https://github.com/techartorg/bqt/wiki/Environment-variables

This workaround works. Thanks a lot.

Also, I've just upgraded bqt to 1.4.1 recently. This problem seems fixed.
