### ISSUE TITLE
pip install fails to copy startup script if wheel module is installed.

### ISSUE THREAD

**Issue by bob-white** [techartorg/bqt#16]
#15 Gets us really close to a one and done installation process, except when the user has `wheel` installed as pypi defaults to installing a wheeled version by default. Which skips the install script.

Need to figure out how to either adjust the package such that it can't be installed as a wheel (not sure if this is possible, and is probably a terrible long term solution)

Or figure out some other way to finalize the installation after the wheel is installed.

**Comment by hannesdelbeke** [comment]
believe this can be closed, after completing the pip setup cleanup https://github.com/techartorg/bqt/issues/61
