### ISSUE TITLE
update project description to appear in search results

### ISSUE THREAD

**Issue by hannesdelbeke** [techartorg/bqt#38]
can we update the GitHub bqt description?
bqt won't show up when searching in GitHub for "blender qt",  
since it doesn't has the word qt in the description.

current description

> Files to help bootstrap PySide2 with an event loop within Blender

**Comment by Debajyoti111** [comment]
@hannesdelbeke Can you assign this to me?

**Comment by Debajyoti111** [comment]
I have made the PR #39 for the requested update. please check

**Comment by hannesdelbeke** [comment]
changed from 
>Files to help bootstrap PySide2 with an event loop within Blender

to
>A Blender add-on to support & manage Qt Widgets in Blender (PySide2)`

since the event loop isn't part of the code anymore
