### ISSUE TITLE
break command line rendering after bqt installed

### ISSUE THREAD

**Issue by atticus-lv** [techartorg/bqt#55]
cmd: `"mypath/blender.exe" --factory-startup -b "my.blend"`
crashlog [blender.crash.txt](https://github.com/techartorg/bqt/files/10152448/blender.crash.txt)
I throught puting script in blender's startup folder is a bad idea

**Comment by atticus-lv** [comment]
Is this bug fixed? Seems that a great change happended to how pyqt works in blender

**Comment by hannesdelbeke** [comment]
AFAIK if you use `--factory-startup` it should be ok. 
but default behaviour still runs in this bug. so users might not be aware and still encounter this.

ideally bqt can detect if blender runs in batch/render mode, and disable itself automatically. without relying on custom settings from the user.

**Comment by hannesdelbeke** [comment]
bqt now however is an addon, so you can also just disable the addon before you run blender in batch/render mode
