### ISSUE TITLE
Another similar project

### ISSUE THREAD

**Issue by melMass** [techartorg/bqt#6]
Hi,

I'm using PySide2 for parts of a blender plugin I'm making, I based mine around this one:

https://github.com/cube-creative/guibedos/blob/master/guibedos/blender.py

I don't have the time right now to compare it with yours but I will and I thought you might be interested :)

**Comment by bob-white** [comment]
Interesting.
Looks very similar, though I can't see any code that ensures that the Qt-related windows are parented to the blender process.

**Comment by hannesdelbeke** [comment]
storing another link to similar project 
openpype has a qt manager for multiple OS 
they do say it's slow on non windows

https://github.com/ynput/OpenPype/blob/develop/openpype/hosts/blender/api/ops.py
