### ISSUE TITLE
possible option to remove window wrap need

### ISSUE THREAD

**Issue by hannesdelbeke** [techartorg/bqt#66]
right now we wrap blender in a qt window. this is the source of all our current issues.
- focus issue: key stuck https://github.com/techartorg/bqt/issues/60
- exception on closing blender https://github.com/techartorg/bqt/issues/47
- fullscreen operator doesnt work  https://github.com/techartorg/bqt/issues/3
- harder to support qt across different OS https://github.com/techartorg/bqt/issues/75
- missing file name in title bar https://github.com/techartorg/bqt/issues/68
- preferences not saved https://github.com/techartorg/bqt/issues/64
- wrap wrong window https://github.com/techartorg/bqt/issues/65
- https://github.com/techartorg/bqt/issues/72
- https://github.com/techartorg/bqt/issues/45
- https://github.com/techartorg/bqt/issues/48
- https://github.com/techartorg/bqt/issues/29
- https://github.com/techartorg/bqt/issues/21

~~unsure if context overrider for operators run from qt would be solved if not wrapped~~
investigated, it doesn't solve https://github.com/techartorg/bqt/issues/62

### parent widgets to blender with ctypes
using ctypes on our widget windows might solve the parenting instead
https://blenderartists.org/t/floating-windows/1163493/317

### wrap widgets in a window managed by blender
Can we either extend Blender source code, creating an official PR in the blender repo to support empty windows.
Or investigate what we already can do with the current exposed Python code.

### auto parent widgets
> but ideally bqt works with 3rd party widgets and their show function. not requiring altering the show function.
Can we find a way to do this automatically? 

Moved this to it's own issue https://github.com/techartorg/bqt/issues/71

**Comment by hannesdelbeke** [comment]
possible option 2:
use empty window as parent. make it transparent and frameless.
but do children inherit this transparent style? that'd be undesired.

**Comment by juizoi** [comment]
Would love to hear more about this, getting a bunch of bugs because of the wrapping

**Comment by hannesdelbeke** [comment]
Could you make a separate issue for each bug? Would help a lot addressing them

**Comment by hannesdelbeke** [comment]
also for your awareness. 
you can set the sys env var BQT_DISABLE_WRAP to 1 to disable wrapping blender in a QWindow.
only disadvantage is tools wont stay in focus when clicking blender. but a lot of small bugs will dissapear

**Comment by juizoi** [comment]
That's good to know, although we're looking to keep that focus unfortunately

**Comment by hannesdelbeke** [comment]
I can show the qwidget in a sep window. not parented to blender.
But as soon as i use `user32.SetParent` the widget instantly dissapears.

```python
import sys
import ctypes
# import multiprocessing as mp
from PySide2.QtWidgets import QApplication, QWidget

def run_widget(handle):
    app = QApplication.instance()
    exec = False
    if not app:
        app = QApplication(sys.argv)#
        exec = True
    widget = QWidget()
    widget.show()
    
    if exec:
        app.exec_()

    user32 = ctypes.windll.user32

    # def set_tool_window(hwnd):
#    GWL_EXSTYLE=-20
#    WS_EX_TOOLWINDOW=0x00000080
#    user32.SetWindowLongPtrW(widget.winId(), GWL_EXSTYLE, WS_EX_TOOLWINDOW)

    # this line makes the widget dissapear instantly.
    user32.SetParent(widget.winId(), handle)

    return widget

def do():
    import bqt.blender_applications.win32_blender_application as win
    blender_hwnd = win.get_blender_window()
    #p = mp.Process(target=run_widget, args=(blender_hwnd,))
    #p.start()
    return run_widget(blender_hwnd)
```

**Comment by hannesdelbeke** [comment]
the floatingwindows.py script contains various ctypes methods that might prove usefull.
```python
#dupplicate into new windows 
bpy.ops.screen.area_dupli('INVOKE_DEFAULT')
new_window = bpy.context.window_manager.windows[-1]
area = new_window.screen.areas[-1]
space_data = bpy.context.space_data
```
[FloatingWindows.zip](https://github.com/techartorg/bqt/files/11646696/FloatingWindows.zip)

**Comment by hannesdelbeke** [comment]
`bpy.ops.wm.window_new()` creates a new window, can we wrap this in qt. and do that for each widget we show?
this would likely work but require devs to manually call a wrap method everytime they show a widget. 
max and unreal use this setup

**Comment by hannesdelbeke** [comment]
What if we use shiboken wrap? think this allows us to parent qwidgets to blender window without wrapping blender in a qwidget.
>Creates a Python wrapper for a C++ object instantiated at a given memory address - the returned object type will be the same given by the user.
The type must be a Shiboken type, the C++ object will not be destroyed when the returned Python object reach zero references.
If the address is invalid or doesn’t point to a C++ object of given type the behavior is undefined.

- https://doc.qt.io/qtforpython-6/shiboken6/shibokenmodule.html
- example how to use https://discourse.techart.online/t/maya-2017-pyside-2-wrapinstance/6033

**Comment by hannesdelbeke** [comment]
parenting a new blender window to blender main window with ctypes works, but is really buggy.
window also dissapeared in background at some point, and main window was blocked

**Comment by hannesdelbeke** [comment]
this could be doable:
manually manage windows in front or not

- create empty invisible qt window/widget that's in foreground
- parent new widget to this QApp.blender_widget
- start a monitoring loop to check active window.
```python
import ctypes
user32 = ctypes.windll.user32
w = user32.GetActiveWindow()
```
if blender is active, bring the blender_widget to foreground. set flag always on top?
if qt widget that has rootnode blender_widget is active, same
if any other widget is active, always on top is set to false allowing other windows in front

event loop could be in blender, but ideally event loop would be in qt. using qttimers or something. e.g. [anim_bar](https://github.com/techartorg/bqt/blob/master/bqt_demo/anim_bar.py)
since Blender operators that runs constantly mess with debugging in VS code

**Comment by hannesdelbeke** [comment]
Using our own manager seems to work quite well.
if shows widgets in the foreground when any blender window is active, and hides them when blender looses focus. e.g. by going to another app. see test branch https://github.com/techartorg/bqt/tree/research/focus-no-wrap

we'd need to create some kind of "register/wrap widget" method, to add the widget to our manager.

**Comment by hannesdelbeke** [comment]
this has gone in with https://github.com/techartorg/bqt/releases/tag/1.1.0
it automatically works if you disabled qt wrapping for bqt by setting the env var `BQT_DISABLE_WRAP` to `1`
it assumes you parented all widgets with `bqt.widget_manager.add(my_widget)`

**Comment by hannesdelbeke** [comment]
interesting to note that this approach would not only work in Blender, but any software that can run python.
so we could generalise bqt to work with anything, not just blender
