### ISSUE TITLE
update to pyside6

### ISSUE THREAD

**Issue by hannesdelbeke** [techartorg/bqt#67]
update to pyside6

and add support for all other qt bindings. pyside2 pyqt5 pyqt6

**Comment by hannesdelbeke** [comment]
let's try stick to [VFX platform](https://vfxplatform.com/) for default version so still pyqt5 or pyside2 for now

**Comment by melMass** [comment]
Hey, I made the edits here: https://github.com/melMass/bqt/tree/mel/pyside6

One thing not sure if it might be related, I will test it out later, is that I'm getting error on loading and exporting keymaps. (I initially came to open an issue, but then realised it might be the 6 upgrade (although all my test of bqt earlier where always in pyside6))
![image](https://user-images.githubusercontent.com/7041726/235384029-ebbb06ee-5e0f-48ff-a6a1-13468212bf51.png)

**Comment by hannesdelbeke** [comment]
weird enough shiboken is qt related, not sure why that is in that error log. so could be something else going on too.
Since I haven't tested yet w PySide6, I'm not sure what to recommend right now.

**Comment by melMass** [comment]
> bpy.app is not related to anything qt related, since it's a blender default attr: see [docs](https://docs.blender.org/api/current/bpy.app.html).
> 
> It sounds like you did a factory startup, and then your settings were saved, which override your old settings.
> 
> 
> 
> If you click the qt close dialogue, it will save your settings before it closes Blender.
> 
> Did you by any chance do a factory startup, then installed bqt, and then close Blender?

Yep as said I did a factory restart, without manually saving, I initially reported that bug in blender chat as I though it was a bug (since a few version blender defaults to auto save prefs, I hate that, so I guessed it was reenabled by the factory reset, but after disabling bqt and it did not. So something is wrong and the keymap drop-down gets broken too)

**Comment by hannesdelbeke** [comment]
updated to pyside6 in december, updated demo files today
